/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import confi.Conexion;

/**
 *
 * @author 52557
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Conexion con = new Conexion();

    Alumnos obj = new Alumnos();
    Profesores obj1 = new Profesores();
    pagos pag = new pagos();
    pagos_Profesor pag_pr = new pagos_Profesor();

    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r_alumno = new javax.swing.JButton();
        r_profe = new javax.swing.JButton();
        p_alumno = new javax.swing.JButton();
        p_profesor = new javax.swing.JButton();
        adeudos = new javax.swing.JButton();
        ingresos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r_alumno.setText("Registar Alumno");
        r_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_alumnoActionPerformed(evt);
            }
        });

        r_profe.setText("Registrar Profesor");
        r_profe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_profeActionPerformed(evt);
            }
        });

        p_alumno.setText("Pagos Alumno");
        p_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_alumnoActionPerformed(evt);
            }
        });

        p_profesor.setText("Pago profesor");
        p_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_profesorActionPerformed(evt);
            }
        });

        adeudos.setText("Reporte Adeudos");
        adeudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adeudosActionPerformed(evt);
            }
        });

        ingresos.setText("Reporte ingresos/egresos");
        ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/303112547_457928663015625_3488370442922093262_n.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(r_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r_profe, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adeudos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(r_profe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_profesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adeudos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_alumnoActionPerformed
        
        
        if(adeudos.isEnabled()){
            
        
            obj.setVisible(true);
        
            this.dispose();
        }else{
            obj.bloquear();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_r_alumnoActionPerformed

    private void r_profeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_profeActionPerformed
        
        
        if(ingresos.isEnabled()){
            obj1.setVisible(true);
            this.dispose();
        }else{
            obj1.bloquear();
            obj1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_r_profeActionPerformed

    private void p_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_alumnoActionPerformed
        
        if(ingresos.isEnabled()){
            
        
            pag.setVisible(true);
            this.dispose();
        }else{
            pag.bloquear();
            pag.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_p_alumnoActionPerformed

    private void p_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_profesorActionPerformed
        
        if(ingresos.isEnabled()){
            pag_pr.setVisible(true);
            this.dispose();
        }else{
            pag_pr.bloquear();
            pag_pr.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_p_profesorActionPerformed

    private void adeudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adeudosActionPerformed
        Adeudos obj = new Adeudos();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adeudosActionPerformed

    private void ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosActionPerformed
        ingresos obj = new ingresos();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ingresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    public void bloquear(){
        adeudos.setEnabled(false);
        ingresos.setEnabled(false);
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adeudos;
    private javax.swing.JButton ingresos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton p_alumno;
    private javax.swing.JButton p_profesor;
    private javax.swing.JButton r_alumno;
    private javax.swing.JButton r_profe;
    // End of variables declaration//GEN-END:variables
}
